# Dockerfile.dev

# Use a base image with Node.js
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose application port and debugging port
EXPOSE 3011
# EXPOSE 3002
EXPOSE 9229

# Define the command to run the application in debug mode
CMD ["npm", "run", "start:debug"]